### ISSUE TITLE
calc_hairpin() returns all possible results and add min_loop params?

### ISSUE THREAD

**Issue by GuoYu-Peng** [libnano/primer3-py#105]
Hey, can primer3-py add `min_loop`  so we can calculate loop size 4-5 bp of hairpins? And stem size parameters?  
Second, can `calc_hairpin()` return all possible hairpins then we can filter as we wanted. Thanks.

**Comment by benpruitt** [comment]
Both of these requests should be directed to the [primer3 library team](https://github.com/primer3-org/primer3/issues) -- we don't modify or extend the underlying library functionalities as part of `primer3-py` (we want to maintain parity in functionality / behavior). We will sometimes add convenience features on top of the library, but these modifications would require changes to the library C source itself.

**Comment by GuoYu-Peng** [comment]
Ok, thanks.
