### ISSUE TITLE
cannot import name 'thermoanalysis'

### ISSUE THREAD

**Issue by ericeric0101** [libnano/primer3-py#117]
Hello everyone,

I tried to install primer3-py to design primers.
When I use Macbook Air (M1) primer3-py works really well.

However, when I install it in Windows system, although it is installed successfully, it gives ImportError:
cannot import name 'thermoanalysis' from 'primer3' (C:\path\AppData\Local\miniconda3\Lib\site-packages\primer3\__init__.py)

I am new to programming so this might be an easy questions.
Please let me know if you need more information to solve this issue.
Thank you very much.

**Comment by benpruitt** [comment]
Which Python and Windows version are you running? How did you install `primer3-py` (from the package, via pip, etc)? Which version of `primer3-py` did you attempt to install?

**Comment by ericeric0101** [comment]
Hello Ben,
I used Spyder (version 5.4.4 with Python 3.8.10) to program and my OP is Windows 10 (64-bit operating system, x64-based processor).
I installed primer3-py via pip (2.0.0).
It either shows cannot import name or "module 'primer3' has no attribute 'bindings'".
Thank you.

**Comment by ericeric0101** [comment]
the problem is solved now. Thank you
