### ISSUE TITLE
minor bug in primer3/thermoanalysis.pyx

### ISSUE THREAD

**Issue by martinfthomsen** [libnano/primer3-py#122]
Hi Ben,

FYI.
Minor bug popped up while I looked around in the new in your awesome product. The todict() function on the ThermoAnalysis feature failed.

```
>>> ThermoAnalysis().todict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "primer3/thermoanalysis.pyx", line 1085, in primer3.thermoanalysis._ThermoAnalysis.todict
AttributeError: 'ThermoAnalysis' object has no attribute 'temp'. Did you mean: 'temp_c'?

```
Thanks,
Martin

**Comment by benpruitt** [comment]
Thanks for catching this; fixed in #123, #124 (included in `v2.0.1` release, should be live on PyPI later today)
