### ISSUE TITLE
primer3.design_primers -> primer3.designPrimers

### ISSUE THREAD

**Issue by Lcarey** [libnano/primer3-py#125]
it seems design_primers() has been renamed to designPrimers(), so the example code needs to be updated

thanks for writing this!!!

**Comment by benpruitt** [comment]
`primer3-py` used `camelCase` method naming conventions until v1.0.0, at which point we moved it to `snake_case` but retained shim `camelCase` methods with deprecation warnings:

https://github.com/libnano/primer3-py/blob/v1.0.0/primer3/bindings.py#L526
https://github.com/libnano/primer3-py/blob/v1.0.0/primer3/bindings.py#L554

So the example code should utilize `snake_case` and both versions should be importable in `>= v1.0.0`. Are you seeing an `ImportError` when you try to run the example code? Can you check which version of `primer3-py` is installed in your python environment?

**Comment by Lcarey** [comment]
thanks!
I'm on an old version. I'd run upgrade, but didn't bother to confirm that the upgrade worked. all good. thanks
and sorry about that
