### ISSUE TITLE
primer3.bindings.design_primers causes kernel crash

### ISSUE THREAD

**Issue by 25shmeckles** [libnano/primer3-py#126]
When running `bindings.design_primers()` or  `bindings.designPrimers()` from primer3-py v 2.0.1 the jupyter kernel crashes.
I tried with different kernels, Py 3.8 to 3.12, all crashed the same way.
It works fine with the previous versions of the library, but it crashes on the latest version.

This is the crashing code:

```
seq_id = f'chr{row.chr}:{row.start}-{row.end}'
seq_args['SEQUENCE_ID'] = seq_id
seq_args['SEQUENCE_TEMPLATE'] = row.sequence
primers[seq_id] = bindings.design_primers(seq_args, global_args)
```
that gives the following message: 

`The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.`

Here is the log

```
11:32:00.902 [info] Handle Execution of Cells 4 for ~/GitHub/notebooks_dungeon/primer_design.ipynb
11:32:01.020 [error] Disposing session as kernel process died ExitCode: undefined, Reason: 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

11:32:01.020 [info] Dispose Kernel process 1535.
11:32:01.035 [info] End cell 4 execution @ undefined, started @ undefined, elapsed time = 0s
```

Not much info here, unfortunately. I can't understand what is going wrong.

Running it as python script also results in a crash and it gives:

```
1 : 100.0% 		probably primer3_core:primer3/src/libprimer3/libprimer3flex.c:3823, assertion (k < ((sa)->incl_l)) failed
[1]    6437 abort      python primers_design.py
```

**Comment by benpruitt** [comment]
Thanks for reporting this issue. Looks like an assertion in the `primer3` library is failing (the script output is very helpful, by the way): 

```
  /* Set j and k, and sanity check */
  if ((OT_LEFT == otype) || (OT_INTL == otype)) {
    j = h->start;
    three_prime_pos = k = j+h->length-1;
  }  else {
    three_prime_pos = j = h->start-h->length+1;
    k = h->start;
  }
  PR_ASSERT(k >= 0);
  PR_ASSERT(k < TRIMMED_SEQ_LEN(sa));
```

The assertion that is failing is the last line in the above snippet. It looks like `j` and `k` are the start + stop positions of the primer on the template sequence. `j` is 5' of `k` on the template sequence but the end of the primer that it corresponds to is dependent on whether the primer being designed is the "left", "internal" or "right" primer. 

A few questions for you:

1. You mention that this issue doesn't occur on previous versions of `primer3-py`. Does that include `v1.x.x` versions? If it works on `v1.x.x` versions then we can rule out an issue intrinsic to the `primer3` `v2.6.1` migration (that happened in the `v1.0.0` release.
2. Do any of your sequence inputs contain non-IUPAC or non-capital characters?
3. Are you setting any other sequence args or global args outside of the script snippet that you provided?

**Comment by 25shmeckles** [comment]
I am trying to narrow down the problem.
The error is triggered when setting `seq_args['SEQUENCE_INTERNAL_OLIGO'] = ''`
The script works if I change that to a subsequence of my target. Still, I don't think it should crash. It should simply raise the appropriate error.

One more thing, if "seq_args['SEQUENCE_INTERNAL_OLIGO']" is a sequence longer that 36bp, I get `OSError: Specified internal oligo exceeds built-in maximum of 36`. This is at least an error, but surely it is not an `OSError`.


Here is a minimal reproducible example:


```
seq_args={
    'SEQUENCE_ID': '',
    'SEQUENCE_TEMPLATE': '',
    'SEQUENCE_INTERNAL_OLIGO': '',
}


global_args={
    'PRIMER_OPT_SIZE': 25,
    'PRIMER_PICK_INTERNAL_OLIGO': 1,
    'PRIMER_INTERNAL_MAX_SELF_END': 8,
    'PRIMER_MIN_SIZE': 20,
    'PRIMER_MAX_SIZE': 30,
    'PRIMER_OPT_TM': 60.0,
    'PRIMER_MIN_TM': 57.0,
    'PRIMER_MAX_TM': 63.0,
    'PRIMER_MIN_GC': 20.0,
    'PRIMER_MAX_GC': 80.0,
    'PRIMER_MAX_POLY_X': 4,
    'PRIMER_INTERNAL_MAX_POLY_X': 4,
    'PRIMER_SALT_MONOVALENT': 50.0,
    'PRIMER_DNA_CONC': 50.0,
    'PRIMER_MAX_NS_ACCEPTED': 0,
    'PRIMER_MAX_SELF_ANY': 8,
    'PRIMER_MAX_SELF_END': 3,
    'PRIMER_PAIR_MAX_COMPL_ANY': 8,
    'PRIMER_PAIR_MAX_COMPL_END': 3,
    'PRIMER_PRODUCT_SIZE_RANGE': [700,1200],
    'PRIMER_PRODUCT_OPT_SIZE': 1000    
}


template = "GGCGCAGCAGCAGCCCCCACGCCCCGCTCCCCCGCAGTGCGTCGGTCACCGTGTTGGGCAGGTAGCTGCGCACGCTGGTGGTGAAGGCCTCGGGGGGGCCCCCGCGGGCCCCGTCCAGCAGCGCGAAGCCGAAGGCCAGCACGTTCTTCGCGCCGCGCTCGCACAGCCTCTGCAGCACTCGGGCCACCAGCTCCTTCAGGCAGGACACCTGCGGGGGAAGCGCCCTGAGTCGCCTGCGCTGCTCTCCGCATGTCGCTGGTTCCCCCCGGCCGCCCTCAACCCCAGCCGGACGCCGACCCCGGGGAGGCCCACCTGGCGGAAGGAGGGGGCGGCGGGGGGCGGCCGTGCGTCCCAGGGCACGCACACCAGGCACTGGGCCACCAGCGCGCGGAAAGCCGCCGGGTCCCCGCGCTGCACCAGCCGCCAGCCCTGGGGCCCCAGGCGCCGCACGAACGTGGCCAGCGGCAGCACCTCGCGGTAGTGGCTGCGCAGCAGGGAGCGCACGGCTCGGCAGCGGGGAGCGCGCGGCATCGCGGGGGTGGCCGGGGCCAGGGCTTCCCACGTGCGCAGCAGGACGCAGCGCTGCCTGAAACTCGCGCCGCGAGGAGAGGGCGGGGCCGCGGAAAGGAAGGGGAGGGGCTGGGAGGGCCCGGAGGGGGCTGGGCCGGGGACCCGGGAGGGGTCGGGACGGGGCGGGGTCCGCGCGGAGGAGGCGGAGCTGGAAGGTGAAGGGGCAGGACGGGTGCCCGGGTCCCCAGTCCCTCCGCCACGTGGGAAGCGCGGTCCTGGGCGTCTGTGCCCGCGAATCCACTGGGAGCCCGGCCTGGCCCCGACAGCGCAGCTGCTCCGGGCGGACCCGGGGGTCTGGGCCGCGCTTCCCCGCCCGCGCGCCGCTCGCGCTCCCAGGGTGCAGGGACGCCAGCGAGGGCCCCAGCGGAGAGAGGTCGAATCGGCCTAGGCTGTGGGGTAACCCGAGGGAGGGGCCATGATGTGGAGGCCCTGGGAACAGGTGCGTGCGGCGACCCTTTGGCCGCTGGCCTGATCCGGAGACCCAGGGCTGCCTCCAGGTCCGGACGCGGGGCGTCGGGCTCCGGGCACCACGAATGCCGGACGTGAAGGGGAGGACGGAGGCGCGTAGACGCGGCTGGGGACGAACCCGAGGACGCATTGCTCCCTGGACGGGCACGCGGGACCTCCCGGAGTGCCTCCCTGCAACACTTCCCCGCGACTTGGGCTCCTTGACACAGGCCCGTCATTTCTCTTTGCAGGTTCTCAGGCGGCGAGGGGTCCCCACCATGAGCAAACCACCCCAAATCTGTTAATCACCCACCGGGGCGGTCCCGTCGAGAAAGGGTGGGAAATGGAGCCAGGCGCTCCTGCTGGCCGCGCACCGGGCGCCTCACACCAGCCACAACGGCCTTGACCCTGGGCCCCGGCACTCTGTCTGGCAGATGAGGCCAACATCTGGTCACATCCCGCCCGCACAGGGTGGAGGGCAACCTCGGGGTC"

seq_args['SEQUENCE_ID'] = "test"
seq_args['SEQUENCE_TEMPLATE'] = template
#seq_args['SEQUENCE_INTERNAL_OLIGO'] = template[500:-500] #OSError
seq_args['SEQUENCE_INTERNAL_OLIGO'] = "" #crash
primers = bindings.design_primers(seq_args, global_args)
```

**Comment by benpruitt** [comment]
I'm not the best person to ask about the `primer3` design engine (I generally write my own primer design algorithms using the low level bindings) -- might be better to direct this kind of question to the `primer3` community over at https://github.com/primer3-org/primer3/issues. That being said, here's what I can glean from the manual:

1. Set `SEQUENCE_TARGET` to `[(start_index, length)]`, specifying the start index and length of the target region (that you want your amplicon to include) within the template. 
2. Set `PRIMER_PRODUCT_OPT_SIZE` to `1000`. Alternatively, you could set `PRIMER_PRODUCT_SIZE_RANGE` to something like `[(900,1100)]`. `PRIMER_PRODUCT_SIZE_RANGE` [defaults](https://primer3.org/manual.html#PRIMER_PRODUCT_SIZE_RANGE) to `100-300` so it might be necessary to set / update both parameters. 

(as a reminder, `PRIMER_` parameters are in the `global_args` whereas `SEQUENCE_` parameters are in the `seq_args`)

Hope this helps; it's been many years since I've used the `primer3` design engine so the above is primarily based on my read of the latest manual and not recent anecdotal experience.
