### ISSUE TITLE
Issues installing on windows10 x86-64

### ISSUE THREAD

**Issue by lucienalperstein** [libnano/primer3-py#128]
Hi,
Trying to install via `pip3 install primer3.py` in VSCode in windows10 and am running into some trouble building getting the following error:
`      copying build\lib.win-amd64-cpython-312\primer3\__init__.py -> build\bdist.win-amd64\wheel\.\primer3
      'mingw32-make' is not recognized as an internal or external command,
      operable program or batch file.
      'mingw32-make' is not recognized as an internal or external command,
      operable program or batch file.
      error: [Errno 2] No such file or directory: 'C:\\Users\\z3290020\\AppData\\Local\\Temp\\pip-install-v5mwmhz0\\primer3-py_534fb369035f44e9a35eb8115051c867\\primer3\\src\\libprimer3\\amplicon3_core.exe'
      [end of output]`

Any ideas on how to solve this error? 
I have MinGW installed but not sure where to start. Thanks for your time!

**Comment by benpruitt** [comment]
Looks like you're using Python 3.12 -- let me roll a patch release with 3.12 wheel support (we've been meaning to do this anyway) and then you won't have to build locally. 

As far as the above error is concerned -- my guess is that `mingw32-make` isn't on your `PATH`. Not sure which instructions you followed to install it, but you might try following [step 7 in this VS Code guide](https://code.visualstudio.com/docs/cpp/config-mingw#_installing-the-mingww64-toolchain) to see if that helps.

**Comment by lucienalperstein** [comment]
@benpruitt successfully installed into a Python 3.12 env using pip, thank you!

**Comment by benpruitt** [comment]
Happy to hear it!
