### ISSUE TITLE
Compiled python program to .exe including Primer3-py does not run - "longjump" / Segmentation Fault

### ISSUE THREAD

**Issue by pcorkos** [libnano/primer3-py#145]
Hello,

When trying to compile a program I'm developing for other users to a simple .exe using pyinstaller, I noticed that the program no longer works, simply printing "longjump" and terminating the popup window. In search to see if this was a pyinstaller issue, I tried compiling with nuitka which converts the python to C/C++, hoping this would resolve the issue.

Unfortunately, the same issue occurred, with nuitka offering its own print statement regarding an unusual segmentation fault. Please let me know if this is something that can be resolved, or if I should be reworking my program to directly interact with Primer3.

**Comment by benpruitt** [comment]
I'm not aware of any other projects using `primer3-py` with `pyinstaller` -- it's certainly not something that we support / have tested as part of maintaining the project.
