### ISSUE TITLE
PRIMER_INTERNAL_EXPLAIN used in output instead of PRIMER_PAIR_EXPLAIN

### ISSUE THREAD

**Issue by dhauge** [libnano/primer3-py#19]
When 'PRIMER_EXPLAIN_FLAG' is enabled and primer3-py is configured to search for primer pairs, the tag emitted to explain primer pair statistics is 'PRIMER_INTERNAL_EXPLAIN' instead of 'PRIMER_PAIR_EXPLAIN'.

This looks like it is just a typo in the line [https://github.com/libnano/primer3-py/blob/master/primer3/src/primerdesign_helpers.c#L1012], where the string should be changed to "PRIMER_PAIR_EXPLAIN".

**Comment by benpruitt** [comment]
Thanks for catching this -- you're definitely correct about the typo. I'll push a fix shortly.
