### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by lmdu** [libnano/primer3-py#20]
Hi,
We attempted to install primer3-py on windows 7 64bit system and got a build error:

`cl: command line error D8021: invalid numeric argument '/Wno-error=declaration-after-statement'
error: command cl.exe failed with exit status 2
`

We hope you can provide wheel for windows. 
Thank you

**Comment by grinner** [comment]
We should probably do that.  Hopefully we can make time in the next few days.3

**Comment by johndeyrup** [comment]
This still seems broken

**Comment by lmdu** [comment]
I have successfully builded primer3-py for windows using `[Mingwpy](https://mingwpy.github.io/)`, a toolchain for building Python extensions for Windows. We hope you can provide official windows buildings

**Comment by grinner** [comment]
Looks like I fixed the windows build awhile ago (before December I believe).  We just need to build the wheels.  I will talk to @benpruitt about this.

**Comment by grinner** [comment]
I think I have it solved for Python 3.5 and 3.6.  reopen the issue if there is problems.
