### ISSUE TITLE
Cannot compile and install in linux ascii Error

### ISSUE THREAD

**Issue by wkpalan** [libnano/primer3-py#26]
`100000 loops, best of 3: 4.74 µs per loop` 

µ symbol in Line 31 seems to be throwing an error when compiling in linux. This crashes pip install in my Ubuntu machine.

`Collecting primer3-py
  Using cached primer3-py-0.5.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4c7jaumj/primer3-py/setup.py", line 52, in <module>
        LONG_DESCRIPTION = fd.read()
      File "/media/data/lab_data/website/simple-primer3-rest-api/venv/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1150: ordinal not in range(128)
`

**Comment by wkpalan** [comment]
Thanks for fixing...

**Comment by benpruitt** [comment]
Of course -- thanks for catching this, surprised it hasn't come up before given all of the ASCII/Unicode issues across various Python versions.
