### ISSUE TITLE
AttributeError: module 'primer3' has no attribute 'calcEndStability'

### ISSUE THREAD

**Issue by billzt** [libnano/primer3-py#34]
```
primer3.calcEndStability('CCCCCATCCGATCAGGGGG', 'CCCCCATCCTATCAGGGGG')
```

returns:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'primer3' has no attribute 'calcEndStability'
```

**Comment by benpruitt** [comment]
Looks like, for whatever reason, that isn't imported and available at the top `primer3` module level. Try `primer3.bindings.calcEndStability` for now and we'll make sure the import is included in the next release.

**Comment by billzt** [comment]
Yes, `primer3.bindings.calcEndStability` gives the correct result.
