### ISSUE TITLE
return multiple ThermoResult objects

### ISSUE THREAD

**Issue by cooketho** [libnano/primer3-py#36]
Would it be possible for calcHomodimer, calcHeterodimer, and calcHairpin to return multiple ThermoResults objects, instead of just a single object with the lowest free energy?

**Comment by benpruitt** [comment]
It's not possible w/ the current `primer3` library (`2.3.7` -- `2.4.0`); however, there is an open issue toward that end here: https://github.com/primer3-org/primer3/issues/30.
