### ISSUE TITLE
result of bindings.designPrimer() function

### ISSUE THREAD

**Issue by juechenyang** [libnano/primer3-py#40]
Hi,

I am using this module to generate primer. However for attributes like “PRIMER_LEFT_4_SELF_ANY”, I only see the results that contain "PRIMER_LEFT_4_SELF_ANY_TH" which means they are calculated by thermodynamical approach. I wonder why I cannot see the value of "PRIMER_LEFT_4_SELF_ANY" that are not calculated by thermodynamical approach. I attached my code for you to review:

seq_args = {
        'SEQUENCE_ID': 'example1',
        'SEQUENCE_TEMPLATE': sequence_template,
        'SEQUENCE_INCLUDED_REGION': [200,1000]
    }
    global_args = {
        'PRIMER_PICK_LEFT_PRIMER':1,
        'PRIMER_PICK_INTERNAL_OLIGO':1,
        'PRIMER_PICK_RIGHT_PRIMER':1,
        'PRIMER_NUM_RETURN':10,
        'PRIMER_MIN_3_PRIME_OVERLAP_OF_JUNCTION':4,
        'PRIMER_MIN_5_PRIME_OVERLAP_OF_JUNCTION':7,
        'PRIMER_MIN_SIZE': 18,
        'PRIMER_MAX_SIZE': 22,
        'PRIMER_OPT_TM': 60.0,
        'PRIMER_MIN_TM': 57.0,
        'PRIMER_MAX_TM': 63.0,
        'PRIMER_PRODUCT_SIZE_RANGE': [[70, 150]]
    }
    binding_res = bindings.designPrimers(seq_args, global_args)

Thanks for your time!

**Comment by benpruitt** [comment]
Based on my read-through of the C source it appears that outputs like `PRIMER_LEFT_4_SELF_ANY` are provided _either_ using the thermodynamic approach (the default, resulting in the `_TH`-suffixed outputs) or explicitly without using the thermodynamic approach. It looks like you can change the default behavior by passing `'PRIMER_THERMODYNAMIC_OLIGO_ALIGNMENT': 0`.

**Comment by juechenyang** [comment]
> 
> 
> Based on my read-through of the C source it appears that outputs like `PRIMER_LEFT_4_SELF_ANY` are provided _either_ using the thermodynamic approach (the default, resulting in the `_TH`-suffixed outputs) or explicitly without using the thermodynamic approach. It looks like you can change the default behavior by passing `'PRIMER_THERMODYNAMIC_OLIGO_ALIGNMENT': 0`.

Hi Ben,

Thanks so much for your help! It did work so well. I do have another question regarding to parameter settings in Primer3-py. Because I am trying to get the result of primer-blast in NCBI portal: https://www.ncbi.nlm.nih.gov/tools/primer-blast/index.cgi
I attached a picture for your reference and wonder if these parameters can be also adjusted in primer3-py. Thanks so much for your time!
![question_for_primer3](https://user-images.githubusercontent.com/18729321/87896962-75544a80-ca0f-11ea-8bca-b55fec52f5db.jpg)

**Comment by benpruitt** [comment]
I believe that some, if not all, of those settings are exposed through parameterization of `primer3`. That being said, those that require `BLAST` will not be exposed through `primer3-py` (which just sits on top of the `primer3` C library). I'd recommend that you review the `primer3` manual to determine which parameters may suit your needs. The maintainers of `primer3-py` are not the authors of `primer3`, so if you have more specific questions about how `primer3` works then I suggest that you contact them. `primer3` itself is now maintained on GitHub as well: https://github.com/primer3-org/primer3

**Comment by juechenyang** [comment]
Thanks Ben. Really appreciate your help and explaination!

Jason
