### ISSUE TITLE
The way of calculating top 2 or top 3 possible dimers.

### ISSUE THREAD

**Issue by ltnetcase** [libnano/primer3-py#41]
I have a problem about high through put PCR process, when template sequences may not be in fixed sequences, and primer oligos may occasionally bind to an unexpected position for some of our samples in different percentage.

I wonder if there is a way in the package to give top 2 or top 3 possible hetero/homo dimers or hairpins to facilitate the evaluation of the effectiveness of primer design. e.g. the second dimer TM is only the first dimer (melting) TM minus 1 centi-degree, then I can filter the primer out in design. 

Would you please point me to that method, or add this feature in your next release?
Thanks in advance.

**Comment by benpruitt** [comment]
Please see the note in our README:

> **Please note that while we provide bindings, we do not provide support for the Primer3 design engine. Please contact the Primer3 dev team with your questions: https://github.com/primer3-org/primer3 **

We just provide bindings into the `primer3` design engine; our goal is to maintain functional equivalence to the command line invocation of the standard binaries (with better performance). Requests like this should be directed to the mainline `primer3` team.
