### ISSUE TITLE
Can't import from within in a jupyter notebook

### ISSUE THREAD

**Issue by hainesm6** [libnano/primer3-py#43]
## Issues

The following line of code returns the following error when run in a ipynb:

```python
from primer3 import bindings

ImportError: cannot import name 'bindings' from 'primer3' (unknown location)
```

## Additional information

The above import statement works when not working in a jupyter environment. Other packages e.g. pandas, can be imported while in the jupyter environment. Running the following suggests primer3-py is installed in site packages:

```bash
$ pip list | grep primer3
primer3-py         0.6.1
```

Any thoughts???

**Comment by benpruitt** [comment]
@hainesm6 -- I'm assuming you ultimately sorted this out?

**Comment by hainesm6** [comment]
Hi @benpruitt ! Thanks for checking up on this. Yes, I believe I found a workaround.

**Comment by benpruitt** [comment]
Ok great -- sorry we didn't get back to you when you first opened the issue. We automated packaging (via GitHub actions) and simplified the actual `primer3` C bindings in `1.0.0` so hopefully that will help mitigate instances of broken installs like this. I'll close this issue for now; please open a new issue if the problem recurs.
