### ISSUE TITLE
Different dimers from ntthal

### ISSUE THREAD

**Issue by billzt** [libnano/primer3-py#44]
Suppose an oligo `GAGGACCTGCGTGTTGTACA`:

In ntthal
```
$ ntthal -s1 GAGGACCTGCGTGTTGTACA -s2 GAGGACCTGCGTGTTGTACA -a END2
Calculated thermodynamical parameters for dimer:        dS = -122.81    dH = -41100     dG = -3010.57   t = -14.6137
SEQ     GAGGACCTGCGTGTT     --------------
SEQ                    GTACA
STR                    CATGT
STR                   A     TGTGCGTCCAGGAG
```

Dimers are connected by 3' ends.

In primer3-py:
```
>>> i = primer3.calcHomodimer('GAGGACCTGCGTGTTGTACA', output_structure=True)
>>> i
ThermoResult(structure_found=True, tm=-10.38, dg=-4327.85, dh=-38200.00, ds=-109.21)
>>> print(i.ascii_structure)
SEQ                G   A   GCGTGTTGTACA
SEQ                 AGG CCT
STR                 TCC GGA
STR     ACATGTTGTGCG   A   G-----------
```

Dimers are connected by 5' ends.

Why so different? How can I get similar results as `ntthal`?

**Comment by benpruitt** [comment]
You're passing the `-a END2` argument to `ntthal` -- `calc_homodimer` uses the equivalent of `-a ANY`. `END2` is specifically looking at `5'` interactions while `ANY` is considering the most stable general homodimer structure. 

You get the same results with `ntthal` if you run it as follows:

```
$ ./ntthal -s1 GAGGACCTGCGTGTTGTACA -s2 GAGGACCTGCGTGTTGTACA -a ANY
Calculated thermodynamical parameters for dimer:	dS = -109.212	dH = -38200	dG = -4327.85	t = -10.38
SEQ	           G   A   GCGTGTTGTACA
SEQ	            AGG CCT
STR	            TCC GGA
STR	ACATGTTGTGCG   A   G-----------
```

`primer3-py` doesn't currently have support for `-a END2`; however, it does have support for `-a END1` (in [calc_end_stability](https://libnano.github.io/primer3-py/api/bindings.html#primer3.bindings.calc_end_stability))
