### ISSUE TITLE
add calcEndStability to __init__.py

### ISSUE THREAD

**Issue by stephen-tanner** [libnano/primer3-py#46]
In the main __init__.py function, there's an import statement that exposes members from .bindings.  I suggest adding calcEndStability to this list (see below).  That would allow for calling primer3.calcEndStability directly (which is currently not possible).  Currently a caller can access primer3.calcHomodimer directly but must call primer3.bindings.calcEndStability to access the calcEndStability functionality.

```
from .bindings import (calcHairpin, calcHomodimer, calcHeterodimer,
                       calcHairpinTm, calcHomodimerTm, calcHeterodimerTm,
                       calcTm, setP3Globals, setP3SeqArgs, runP3Design,
                       designPrimers, calcEndStability)
```

Best Regards,
--Stephen Tanner

**Comment by 25shmeckles** [comment]
I was going to open the same issue. Contrary to what is stated in the docs, calling `primer3. calcEndStability` results in `AttributeError: module 'primer3' has no attribute 'calcEndStability'`
