### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by InvisOn** [libnano/primer3-py#47]
It is unclear from the existing documentation what [thal_type](https://libnano.github.io/primer3-py/api/thermoanalysis.html#primer3.thermoanalysis.ThermoAnalysis.thal_type) refers to.

I've had to look in the source code to find the corresponding parameter in the [primer3 manual](https://primer3.org/manual.html).

I'm assuming [PRIMER_THERMODYNAMIC_OLIGO_ALIGNMENT](https://primer3.org/manual.html#PRIMER_THERMODYNAMIC_OLIGO_ALIGNMENT)

Furthermore, [tm_method](https://libnano.github.io/primer3-py/api/thermoanalysis.html#primer3.thermoanalysis.ThermoAnalysis.tm_method) mentions TM_METHODS. Yet, TM_METHODS does not exist. It seems  [PRIMER_TM_FORMULA](https://primer3.org/manual.html#PRIMER_TM_FORMULA) is correct.

**Comment by grinner** [comment]
Addressed in PR #79
