### ISSUE TITLE
primer3 moved from sourceforge to GitHub

### ISSUE THREAD

**Issue by peterjc** [libnano/primer3-py#49]
The project pages on SourceForge are out of date, https://sourceforge.net/projects/primer3/files/ only goes up to v2.4.0 - however there are links to http://primer3.org/ 

As per links on http://primer3.org/ the repository is now at https://github.com/primer3-org/primer3 (currently at v2.5.0,  August 2019)

Various links in the documentation need to be updated, and potentially the binding themselves?

**Comment by peterjc** [comment]
I note your documentation says "The included libprimer3 source is a dervative of the Primer3 v2.3.7 library"
https://libnano.github.io/primer3-py/miscellany.html#derivative-work

(Note typo, "dervative" --> "derivative")

According to the release notes, there have only been two releases since v2.3.7, which were v2.4.0 in November 2017 and v2.5.0 in August 2019 - several of the changes seem relevant:

https://github.com/primer3-org/primer3/blob/master/src/release_notes.txt

**Comment by peterjc** [comment]
See also #48 on updating the code - I had intended this issue to focus on updating the documentation.

**Comment by diekhans** [comment]
https://libnano.github.io/primer3-py/quickstart.html#primer-design links to 
http://primer3.sourceforge.net/primer3_manual.htm, which does not exist

**Comment by peterjc** [comment]
That's exactly the kind of thing I had in mind for this issue @diekhans, if you wanted to submit a pull request with a newer link instead you'd edit file https://github.com/libnano/primer3-py/blob/master/docs/quickstart.rst

(Unfortunately there are now a couple of open pull requests for minor documentation fixes, so I wouldn't expect the maintainers to merge it right away)

**Comment by benpruitt** [comment]
`primer3-py` now includes `primer3` `v2.6.1` as of the [v1.0.0 release](https://github.com/libnano/primer3-py/releases/tag/v1.0.0) -- we also went through and updated all of the stale `SourceForge` links in the documentation (and @grinner added GH action-based doc builds so hopefully we can better avoid documentation coherence issues in the future)
