### ISSUE TITLE
SEQUENCE_OVERLAP_JUNCTION_LIST

### ISSUE THREAD

**Issue by juechenyang** [libnano/primer3-py#51]
Hi

I have a question about what should I input in bindings.designPrimers() if I want to adjust SEQUENCE_OVERLAP_JUNCTION_LIST in primer3? I have test many input types (like list[], list of list[[],[]] or even single number) and they all returned to me with same results. So I feel like there is something wrong with my input. Would you mind help me with this?

**Comment by benpruitt** [comment]
It looks like we expect `SEQUENCE_OVERLAP_JUNCTION_LIST` to be a list of integers (similar to the space-delimited list expected by the `primer3` binaries). If you can send along some sample code to reproduce the issue I can take a look.

**Comment by janicel** [comment]
Hi! I am experiencing the same issue. Adding `SEQUENCE_OVERLAP_JUNCTION_LIST` does not change the outputs. I looked at the  source code and noticed that in the file `primer3/src/primerdesign_helpers.c` line 721 is commented out:
`// DICT_GET_AND_COPY_ARRAY_INTO_ARRAY(p_obj, sa_dict,  "SEQUENCE_OVERLAP_JUNCTION_LIST", &sa->primer_overlap_junctions, overlap_junction_len);`

Not sure if this is the issue? Would you be able to look at that? Thank you for your time!

**Comment by janicel** [comment]
okay I found out why. I was putting the input at the wrong place. It should be in the first dictionary with the sequence. Thank you!
