### ISSUE TITLE
bad link in  quickstart documentation

### ISSUE THREAD

**Issue by diekhans** [libnano/primer3-py#55]
https://libnano.github.io/primer3-py/quickstart.html#id6 links to 

http://primer3.sourceforge.net/primer3_manual.htm

which is not valid, I believe the correct link is

https://primer3.org/manual.html

**Comment by benpruitt** [comment]
Fixed in the [v1.0.0 release](https://github.com/libnano/primer3-py/releases/tag/v1.0.0) -- we addressed all of the stale `SourceForge` links and bumped the `primer3` library version to the latest ([2.6.1](https://github.com/primer3-org/primer3/releases/tag/v2.6.1))
