### ISSUE TITLE
primer3 2.6.0 feature

### ISSUE THREAD

**Issue by sanjaynagi** [libnano/primer3-py#56]
Is there any scope for updating the primer3 version in primer3-py?

The 2.6.0 version adds an internal oligo parameter - SEQUENCE_INTERNAL_OVERLAP_JUNCTION_LIST which would be very useful for probe design. Thanks!

**Comment by benpruitt** [comment]
`primer3-py` now includes `primer3` `v2.6.1` as of the [v1.0.0 release](https://github.com/libnano/primer3-py/releases/tag/v1.0.0) -- `SEQUENCE_INTERNAL_OVERLAP_JUNCTION_LIST` is now supported through the design binding (and there is test coverage w/ the `primer_internal_position_input` test input file).
