### ISSUE TITLE
Can `primer3-py` support the degenerate base design ?

### ISSUE THREAD

**Issue by kevin2022lee** [libnano/primer3-py#57]
Can primer3.py support the degenrate base design ?
like this
[![微信截图_20220810104631](https://23img.com/i/2022/08/10/hag8e8.png)](https://23img.com/l/?i=/i/2022/08/10/hag8e8.png)
[![微信截图_20220810104643](https://23img.com/i/2022/08/10/hagevt.png)](https://23img.com/l/?i=/i/2022/08/10/hagevt.png)
[![微信截图_20220810104656](https://23img.com/i/2022/08/10/hagjef.png)](https://23img.com/l/?i=/i/2022/08/10/hagjef.png)
when i input this sequence ,J got some errors

[![微信截图_20220810105242](https://23img.com/i/2022/08/10/hbmnsx.png)](https://23img.com/l/?i=/i/2022/08/10/hbmnsx.png)

please contact me email lxk@kodiabio.com .let me know!

**Comment by peterjc** [comment]
Cross reference #59 on improving the message "Unrecognized base in input sequence".

As a workaround, try replacing those ambiguity codes with N instead.

**Comment by kevin2022lee** [comment]
> Cross reference #59 on improving the message "Unrecognized base in input sequence".
> 
> As a workaround, try replacing those ambiguity codes with N instead.

def reverseOligo(ss):
    if len(ss)!= 0:
        re_seq=''
        strss=str(ss)
        for s in strss:
#             global re_seq
            if s=='A':
                re_s='T'
                re_seq=re_seq+re_s
            elif s=='T':
                re_s='A'
                re_seq=re_seq+re_s
            elif s=='G':
                re_s='C'
                re_seq=re_seq+re_s
            elif s=='C':
                re_s='G'
                re_seq=re_seq+re_s
            elif s=='R':
                re_s='Y'
                re_seq=re_seq+re_s
            elif s=='Y':
                re_s='R'
                re_seq=re_seq+re_s
            elif s=='M':
                re_s='K'
                re_seq=re_seq+re_s
            elif s=='K':
                re_s='M'
                re_seq=re_seq+re_s
            elif s=='S':
                re_s='S'
                re_seq=re_seq+re_s
            elif s=='W':
                re_s='W'
                re_seq=re_seq+re_s
            elif s=='H':
                re_s='D'
                re_seq=re_seq+re_s
            elif s=='B':
                re_s='V'
                re_seq=re_seq+re_s
            elif s=='V':
                re_s='B'
                re_seq=re_seq+re_s
            elif s=='D':
                re_s='H'
                re_seq=re_seq+re_s
            elif s=='N':
                re_s='N'
                re_seq=re_seq+re_s
            
    return re_seq[::-1]

**Comment by kevin2022lee** [comment]
It works！

**Comment by grinner** [comment]
@kevin2022lee we will add a degenerate base sequence generator to the roadmap we are working on.

**Comment by grinner** [comment]
PR #98 for 1.2.0 fixes this issue

**Comment by kevin2022lee** [comment]
you can try my app online here


the primer is reverse complement of the target sequence .










BESTS
李先坤/Kevin Lee
部门 / Dept：研发部 / R.D.
*****************************************************************************************

-----------------------------------------------------------------------------------------
地址 / Add ：郑州市高新区莲花街352号高新国际企业港23号楼
电话 / Tel ：+86 0371-67890306     手机 /Mobile：+86 15639270937
邮件 / E-mail ***@***.***
集团网站 / Website ：www.norsonmed.com
******************************************************************************************



发件人：Peter Cock ***@***.***>
发送日期：2022-08-25 19:21:19
收件人：libnano/primer3-py ***@***.***>
抄送人：kevin2022lee ***@***.***>,Author ***@***.***>
主题：Re: [libnano/primer3-py] Can primer3.py support the degenrate base design ? (Issue #57)

Cross reference #59 on improving the message "Unrecognized base in input sequence".
As a workaround, try replacing those ambiguity codes with N instead.

**Comment by kevin2022lee** [comment]
I found some bugs on this issue for new release v1.2.0 .
File "setup.py", line 187
f'{MAKE_BIN} clean',
^
SyntaxError: invalid syntax
I try pip install or python setup.py intall
the same error
please fix it








李先坤/Kevin Lee
部门 / Dept：研发部 / R.D.
*****************************************************************************************

-----------------------------------------------------------------------------------------
地址 / Add ：郑州市高新区莲花街352号高新国际企业港23号楼
电话 / Tel ：+86 0371-67890306     手机 /Mobile：+86 15639270937
邮件 / E-mail ***@***.***
集团网站 / Website ：www.norsonmed.com
******************************************************************************************



发件人：Nick Conway ***@***.***>
发送日期：2023-03-02 01:00:27
收件人：libnano/primer3-py ***@***.***>
抄送人：kevin2022lee ***@***.***>,Mention ***@***.***>
主题：Re: [libnano/primer3-py] Can primer3.py support the degenrate base design ? (Issue #57)

@kevin2022lee we will add a degenerate base sequence generator to the roadmap we are working on.

**Comment by peterjc** [comment]
@kevin2022lee that's unrelated to issue #57, rather it is Python 3 syntax being used under Python 2. I believe the library needs at least Python 3.8, but it could make that clearer. You need to use a current version of Python.
