### ISSUE TITLE
Wheels for python 3.9+

### ISSUE THREAD

**Issue by JacobHayes** [libnano/primer3-py#58]
Hi, any chance new wheels could be made for py 3.9, 3.10 and maybe 3.11? We're having some flakey installations (via `pipenv`, but not via `pip` directly 🤔) that were seemingly only fixed after removing the `primer3-py` dep (which we obviously don't want to do 😄).

I don't _think_ that would require a new release (iirc, pypi will allow you to upload _new_ files), but might be safer anyway if that'd be possible. Thanks!

**Comment by benpruitt** [comment]
Which OS? I just uploaded `3.9` and `3.10` wheels for macOS. `3.11` won't be released until October. 

Would you be able to share any of the output from your erroneous `pipenv` installs? We can try to address any identifiable issues in the next `primer3-py` release.

**Comment by JacobHayes** [comment]
Thanks! macOS is the main one, but we also deploy on linux (I know the `manylinux` wheels can be a bit trickier though).

Unfortunately, `pipenv`'s errors aren't very helpful (I can't quite find my verbose logs anymore, but I don't remember that having much info either). It just showed:
```
An error occurred while installing primer3-py==0.6.1 --hash=sha256:4bdec6b5a3b39b5715eef968ecf47e419fea014080cca20e8f2ed6a97a7ca076 --hash=sha256:d0076e42aa3d4c05adcc26bbea4635be0d7ce3b53e289b83326077d90e6659d6 --hash=sha256:0cc93abc0406e2c095c338bbdeaab001335748b91310e14b0148975aed45b338 --hash=sha256:e155c76aaa42ea8dbb95629371f6fb2068da660bd8d934fa49dba50e9294963c --hash=sha256:2d26671017d57ee37c5d5c430eb1545d8765f3d31782e9d7c0cdd9b5a22b2b8b --hash=sha256:e44e068ca4f03c7df1dea0de2582c9d1fb83082d6dab4908d12fd680b0801bde --hash=sha256:f1058150c6aa0b6a1c547c3437ebcac8d68130974b71a8635d79d992f8b25a29 --hash=sha256:b45c96632ffd2d573584f08c335ccae0007a6f1f06337fec3b68fd856f00f4f7 --hash=sha256:44020e414f77420028b3d8532077972d71d7f9a5f5114b192afa2010971c0057 --hash=sha256:c31ff57ef835d538b44d9c7f8a268d0023b51ead2c4fef65936029e3c0cd5f38 --hash=sha256:faa40b5034e474e8af3d5cebed2f91684eb144b2c25f534795b2e6ed2eb6ef40! Will try again.
```
I'll close this for now, but can add more info and re-open if I see it again. Thanks again!
