### ISSUE TITLE
Message "Unrecognized base in input sequence" omits problem char

### ISSUE THREAD

**Issue by peterjc** [libnano/primer3-py#59]
I have run into an example failing with ``Unrecognized base in input sequence``, without being told what the problematic base is.

Quoting ``src/libprimer3/libprimer3.c`` this warning/error message does not but could easily report the offending character:

```C
  if ((offending_char = dna_to_upper(sa->trimmed_seq, 0))) {
    if (pa->liberal_base) {
      pr_append_new_chunk(warning,
                          "Unrecognized base in input sequence");
    } else {
      pr_append_new_chunk(nonfatal_err,
                          "Unrecognized base in input sequence");
      return 1;
    }
  }
```

**Comment by peterjc** [comment]
In fact it might be useful to special case the unrecognized base being one of BDKMRSVWY (or lower case) and report something like "Rejecting non-N IUPAC ambiguity code"?

I am working around this limitation by replacing those bases with N in my input to primer3-py.

**Comment by grinner** [comment]
1.1.0 resolves this issue
