### ISSUE TITLE
add .whl files for python 3.9 and 3.10 in windows

### ISSUE THREAD

**Issue by wpwupingwp** [libnano/primer3-py#62]
Dear author,

Currently primer3-py do not support python `3.9` and `3.10` in `Microsoft Windows` or user have to build from source code by themself, which is chalengeing for normal users.

I have built them in my computer with mingw32. Could you please add them into pypi so that more python version could use primer3-py in Windows?

I did this because I wrote a program which dependent on primer3-py and I hope more Windows users could run it.

The attachment is compressed wheel files because github do not support uploading `.whl` files.

The Powershell script I used:
```powershell
$version="3.7","3.8","3.9","3.10", "3.11"
$src="R:\build\primer3-py-0.6.1"
# edit MAKE_BIN in setup.py if necessary
# use mingw32-make https://github.com/niXman/mingw-builds-binaries/releases/tag/12.2.0-rt_v10-rev2
$python="python"
&cd ${src}
foreach (${f} in ${version})
{
    &py -${f} -m venv ${f}
    &${f}/Scripts/Activate.ps1
    &pip install -U cython build setuptools wheel
    &${python} -m build -n --wheel
    $deactivate
}
&ls ${src}\dist
```
[dist.zip](https://github.com/libnano/primer3-py/files/10313458/dist.zip)

**Comment by benpruitt** [comment]
All set. Thanks for sharing your PowerShell script. We'll improve windows build support and consistency next time we cut a release -- the builds worked in my hands w/ a couple of minor modifications to `setup.py` related to `Makefile` invocation (so outside of the script itself).
