### ISSUE TITLE
Building the sdist fails as header is missing : v1.1.0

### ISSUE THREAD

**Issue by ccoulombe** [libnano/primer3-py#95]
Building from source from the sdist on PyPI fails as the `dpal.h` header is missing:
```
      primer3/src/libprimer3/dpal.c:43:10: fatal error: dpal.h: No such file or directory
         43 | #include "dpal.h"
            |          ^~~~~~~~
```

Building/installing from Github works :
```
pip install https://github.com/libnano/primer3-py/archive/refs/tags/v1.1.0.tar.gz
```

**Comment by ccoulombe** [comment]
Excellent, thanks @benpruitt !

We avoid conda as the pest but looking at the commit this will work with a standard virtual environment and pip install.
In all cases, I can build wheels from the Github sources as well.

I can confirm once the v1.2.0 is released.

**Comment by grinner** [comment]
PR #98 for 1.2.0 fixes this issue
