### ISSUE TITLE
setup.py error!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by kevin2022lee** [libnano/primer3-py#99]
File "setup.py", line 187
    f'{MAKE_BIN} clean',
                      ^
SyntaxError: invalid syntax

I try pip install or python setup.py intall

the same error

please fix it

**Comment by kevin2022lee** [comment]
I recovery my version to  v0.6.0 , it goes well !

**Comment by benpruitt** [comment]
Hi Kevin -- it looks like you are using a pre-`3.8` version of Python ([f-string support](https://peps.python.org/pep-0498/) was added in Python 3.6). As of `primer3-py` `1.0.0`, we no longer support Python `2.7` or `3.x` versions < `3.8`

**Comment by kevin2022lee** [comment]
> Hi Kevin -- it looks like you are using a pre-`3.8` version of Python ([f-string support](https://peps.python.org/pep-0498/) was added in Python 3.6). As of `primer3-py` `1.0.0`, we no longer support Python `2.7` or `3.x` versions < `3.8`

hi,
ben, because I used the biopython libary in my project , so I can t update my python version anywhere .

thanks all the same !

you re nice guy.
